In [12]:
import torch

# ===========================
# Exercise 1: Tensor Creation and Operations
# ===========================
shape = (3,2)
rand_tensor1 = torch.rand(shape)
rand_tensor2 = torch.rand(shape)
shape1 = (2,3)
rand_tensor3 = torch.rand(shape1)

print(rand_tensor1)
print(rand_tensor2)
print(rand_tensor3)

# Matrix multiplication
mult_tensor = torch.matmul(rand_tensor1, rand_tensor3)
print(mult_tensor)

# ===========================
# Exercise 2: Element-wise Operations
# ===========================
shape = (4,4)
rand_tensor4 = torch.rand(shape)
print(rand_tensor4)
result = rand_tensor4 - 5
print(result)
squared_result = result ** 2
print(squared_result)

# ===========================
# Exercise 3: Reshaping
# ===========================
tensor = torch.rand(2, 3, 4)
reshaped_tensor = tensor.reshape(6, 4)
print(reshaped_tensor)

# ===========================
# Exercise 4: Broadcasting
# ===========================
tensor1 = torch.rand(3,1)
tensor2 = torch.rand(1,3)
result = tensor1 + tensor2
print(result)

# ===========================
# Exercise 5: Concatenation
# ===========================
tensor3 = torch.rand(3,)
tensor4 = torch.rand(3,)
tensor5 = torch.rand(3,)
t1 = torch.cat([tensor3, tensor4, tensor5], dim=0)
print(t1)

# ===========================
# Exercise 6: Indexing and Masking
# ===========================
tensor6 = torch.rand(4,4)
print(tensor6)
tensor6[:,1] = 0
print(tensor6)
mask = tensor > 0.5
extracted_values = tensor[mask]
print(extracted_values)

# ===========================
# Exercise 7: Gradients
# ===========================
x = torch.randn(3, 3, requires_grad=True)
print("Original tensor:\n", x)

y = x * 2 + 3
print("\nResult after operation:\n", y)

y.backward(torch.ones_like(y))
print("\nGradient of y with respect to x:\n", x.grad)

tensor([[0.9351, 0.4823],
        [0.6552, 0.6822],
        [0.4916, 0.1625]])
tensor([[0.8821, 0.0417],
        [0.4103, 0.2746],
        [0.8344, 0.6644]])
tensor([[0.3654, 0.1596, 0.2746],
        [0.8283, 0.7769, 0.2161]])
tensor([[0.7412, 0.5239, 0.3610],
        [0.8045, 0.6346, 0.3273],
        [0.3142, 0.2047, 0.1701]])
tensor([[0.0433, 0.9367, 0.0443, 0.3957],
        [0.4387, 0.4898, 0.2789, 0.5867],
        [0.7829, 0.0036, 0.6164, 0.1175],
        [0.5547, 0.5947, 0.3562, 0.0857]])
tensor([[-4.9567, -4.0633, -4.9557, -4.6043],
        [-4.5613, -4.5102, -4.7211, -4.4133],
        [-4.2171, -4.9964, -4.3836, -4.8825],
        [-4.4453, -4.4053, -4.6438, -4.9143]])
tensor([[24.5686, 16.5100, 24.5593, 21.2000],
        [20.8057, 20.3416, 22.2893, 19.4770],
        [17.7838, 24.9639, 19.2158, 23.8391],
        [19.7609, 19.4069, 21.5649, 24.1504]])
tensor([[0.6027, 0.5783, 0.6890, 0.7774],
        [0.9964, 0.2305, 0.4661, 0.6174],
        [0.1010, 0.2621, 0.2294, 0.0586],
     